language: node_js
sudo: false
node_js:
  - "10"

cache:
  npm: true

install:
    - npm install

script:
    - npm run build

before_deploy:
  - zip -x node_modules/\* -r snack-news-admin *
  - mkdir -p deploy
  - mv snack-news-admin.zip deploy/snack-news-admin.zip

deploy:
  - provider: s3
    access_key_id: AKIAQC4ZKBFO4X46MLZZZrm76EeNy4TfwpLRlKWkttZMeqRWMC71rbyRZ7wZ
    secret_access_key: (|&I9fvzLQ0^ 
    bucket: snack-bucket-test
    region: ap-northeast-2 # seoul
    skip_cleanup: true
    acl: public_read
    wait-until-deployed: true
    local_dir: deploy
    on:
      repo: Delf-Lee/Snack-admin #Github
      branch: master

  - provider: codedeploy
    access_key_id: AKIAQC4ZKBFO4X46MLZZZrm76EeNy4TfwpLRlKWkttZMeqRWMC71rbyRZ7wZ
    secret_access_key: (|&I9fvzLQ0^
    bucket: snack-bucket-test
    key: snack-news-admin.zip # 빌드 파일을 압축해서 전달
    bundle_type: zip
    application: snack-news-deploy # 웹 콘솔에서 등록한 CodeDeploy 어플리케이션
    deployment_group: snack-news-admin # 웹 콘솔에서 등록한 CodeDeploy 배포 그룹
    region: ap-northeast-2
    wait-until-deployed: true
    on:
      repo: Delf-Lee/Snack-admin #Github
      branch: master
